services:
  redis:
    image: redis:7-alpine
    container_name: journal-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  app:
    build: .
    container_name: journal-app-container
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - redis
